source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'10.0'

use_frameworks!

target ‘Refuel’ do
    pod 'Alamofire', '5.4.1'
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'R.swift'
end
